CONF_CURRENT_1 = "current_1"
CONF_CURRENT_2 = "current_2"
CONF_CURRENT_3 = "current_3"
CONF_CURRENT_4 = "current_4"
CONF_CURRENT_5 = "current_5"
CONF_CURRENT_6 = "current_6"

CONF_POWER_1 = "power_1"
CONF_POWER_2 = "power_2"
CONF_POWER_3 = "power_3"
CONF_POWER_4 = "power_4"
CONF_POWER_5 = "power_5"
CONF_POWER_6 = "power_6"
CONF_POWER_SUM = "power_sum"

CONF_ENERGY_1 = "energy_1"
CONF_ENERGY_2 = "energy_2"
CONF_ENERGY_3 = "energy_3"
CONF_ENERGY_4 = "energy_4"
CONF_ENERGY_5 = "energy_5"
CONF_ENERGY_6 = "energy_6"
CONF_ENERGY_SUM = "energy_sum"
